
---

extends:
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    - node
    - webpack

rules:
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
  no-param-reassign: 0
  no-unused-vars: ["error", { argsIgnorePattern: "^_" }]
  no-unused-expressions: 0